name: agendamento_app
description: Sistema de agendamento de veículos corporativo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.2.0

  # Navegação
  go_router: ^16.0.0

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.1.0
  firebase_ui_auth: ^1.5.0
  cloud_firestore: ^5.6.11

  # Gerenciamento de estado
  provider: ^6.1.1

  # Utilitários
  intl: ^0.20.2
  desktop_webview_auth: ^0.0.15



  # Gráficos
  fl_chart: ^1.0.0

  # UI & Navegação extra
  google_sign_in: ^6.1.1
  cupertino_icons: ^1.0.8
  syncfusion_flutter_calendar: ^30.1.39
  flutter_form_builder: ^10.1.0
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/