// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO-T0QECEll7DQC3SyRp0zJjtck-LsiD4',
    appId: '1:805720964005:web:00b4b02a258e771790464c',
    messagingSenderId: '805720964005',
    projectId: 'app-agendamento-veiculos',
    authDomain: 'app-agendamento-veiculos.firebaseapp.com',
    storageBucket: 'app-agendamento-veiculos.firebasestorage.app',
    measurementId: 'G-GSJS4MH3QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs8WiB3ZensIhnxurJCVrLBJCWdtNrBuY',
    appId: '1:805720964005:android:0f7027b02b365d3e90464c',
    messagingSenderId: '805720964005',
    projectId: 'app-agendamento-veiculos',
    storageBucket: 'app-agendamento-veiculos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu5kfSe3khKpy4pGIYyQAWgTwdrIcFvMc',
    appId: '1:805720964005:ios:02e5adc8a1a87eae90464c',
    messagingSenderId: '805720964005',
    projectId: 'app-agendamento-veiculos',
    storageBucket: 'app-agendamento-veiculos.firebasestorage.app',
    iosClientId:
        '805720964005-nnu4ekapl4sfephe57urqgjirit1qddp.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendamentoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu5kfSe3khKpy4pGIYyQAWgTwdrIcFvMc',
    appId: '1:805720964005:ios:02e5adc8a1a87eae90464c',
    messagingSenderId: '805720964005',
    projectId: 'app-agendamento-veiculos',
    storageBucket: 'app-agendamento-veiculos.firebasestorage.app',
    iosClientId:
        '805720964005-nnu4ekapl4sfephe57urqgjirit1qddp.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendamentoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO-T0QECEll7DQC3SyRp0zJjtck-LsiD4',
    appId: '1:805720964005:web:13634922ac33283890464c',
    messagingSenderId: '805720964005',
    projectId: 'app-agendamento-veiculos',
    authDomain: 'app-agendamento-veiculos.firebaseapp.com',
    storageBucket: 'app-agendamento-veiculos.firebasestorage.app',
    measurementId: 'G-D9GKCH9Q75',
  );
}
